apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windowsdeveloperarcdemo
  namespace: windowsdeveloper-arcdemo
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: windowsdeveloperarcdemo
  chart: 
    spec:
      chart: ./WindowsDeveloperArcDemo/charts/windowsdeveloperarcdemo