replicaCount: 1

image:
  repository: windevacr.azurecr.io/windowsdeveloperarcdemo # replace with your repository or use wolfgangofner/windowsdeveloperarcdemo
  pullPolicy: Always
  tag: 0.1.6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true  
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

keyvault:
  secretvariable:
    name: SecretValue
    secretRefName: secretvalue
    secretRefKey: secretvalue