apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kvsecretsprovider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ArcDemoKeyVault
    objects:  |
      array:
        - |
          objectName: SecretValue
          objectType: secret             
          objectVersion: ""           
    tenantId: ff8fa635-7b19-4726-90ab-23bf29f8d8d7
  secretObjects:                             
  - secretName: secretvalue
    data:
    - key: secretvalue
      objectName: secretvalue
    type: Opaque           