apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: arcdemo-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ArcDemo-KeyVault # Replace with your Key Vault Name
    objects:  |
      array:
        - |
          objectName: secretvalue
          objectType: secret             
          objectVersion: ""           
    tenantId: <TENANT_ID> # Replace with your Tenant ID
  secretObjects:                             
  - secretName: secretvalue
    data:
    - key: secretvalue
      objectName: secretvalue
    type: Opaque           